import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ChakraClientProvider } from '@/providers/chakra-client-provider'
import { Flex } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height: "100%"}}>
      <body className={inter.className} style={{height: "100%"}}>
        <ChakraClientProvider>
          <Flex direction="row" h="100%">
            <Sidebar/>
            {children}
          </Flex>
        </ChakraClientProvider>
      </body>
    </html>
  );
}
